### ISSUE TITLE
"debug" example crashes

### ISSUE THREAD

**Issue by frol** [maps4print/azul#1]
I am not sure if it is expected on the current state of the project development, but I figured it would rather give some feedback:

```
$ env RUST_BACKTRACE=1 cargo run --example debug
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/debug`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreateError(NoAvailablePixelFormat)', /checkout/src/libcore/result.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: debug::main
             at examples/debug.rs:45
  12: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at /checkout/src/libstd/rt.rs:59
             at /checkout/src/libstd/panicking.rs:480
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  15: std::rt::lang_start_internal
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  16: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  17: main
  18: __libc_start_main
  19: _start
```

* Arch Linux, x86_64, kernel 4.15.10
* Intel HD 4600 video card
* Gnome 3.26.2
* Rust 1.24.0

**Comment by fschutt** [comment]
`CreateError(NoAvailablePixelFormat)'` - I've had this before, it's usually a driver issue. It's probably because of the SRGB extension or the VSync extension. If those aren't found, the window creation crashes. It works fine for me on KDE / Debian 9 and it could probably run if you comment out one of [these two lines](https://github.com/maps4print/azul/blob/master/src/window.rs#L435-L436). Can you test if this fixes the issue? 

Of course, I don't really like disabling VSync and disabling SRGB, because they are really nice to have.

**Comment by frol** [comment]
![screenshot from 2018-03-20 09-43-12](https://user-images.githubusercontent.com/304265/37641616-22eed1ac-2c23-11e8-8659-424162634480.png)

I expected to see numbers in the labels but only see small red squares on the top (once I move my mouse over the button). Is that how it works now or something misbehaves?

**Comment by fschutt** [comment]
Yeah, I think SRGB isn't that big of a deal to disable.. I think I'll make it so that the it retries the context creation on failure, making SRGB / Vsync optional - so that they are enabled on platforms they work on, but aren't strictly required.

Thanks for reporting.

**Comment by fschutt** [comment]
Yeah, that's the current state of the library, I haven't had much more time to work on this. There are no actual buttons, no fonts, etc. This is how it should look like (except it should also show a shadow, but this is a problem with webrender). But the hit-testing works.

**Comment by frol** [comment]
Thanks for the confirmation and blazing fast responses! The project seems to be quite promising, I will keep an eye on it!

**Comment by fschutt** [comment]
@frol Should be fixed now, could you try cloning and building again (I sadly can't test that the "fix" actually worked)?

**Comment by frol** [comment]
It works!
